#!/usr/bin/env bash

help() {
  cat <<EOF
Usage: $(basename "$0") [--username <username>] [--password <password>] [--email <email>]
Ex: c8y oee \create_user --username abctest --password Password.123 --email dummy-oeeadmin@softwareag.com
Create a user with global roles "OEE Admin" and "OEE Reader".
EOF
}

echo "URL       :  $C8Y_HOST"
echo "Tenant ID :  $C8Y_TENANT"
echo "User      :  $C8Y_USER"

# Parse command-line options
REST_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      help
      exit 0
      ;;
    --username)
      if [ $# -gt 1 ]; then
        username=$2
        shift
      else
        echo "Option $1 requires an argument." >&2
        exit 1
      fi
      ;;
    --password)
      if [ $# -gt 1 ]; then
        password=$2
        shift
      else
        echo "Option $1 requires an argument." >&2
        exit 1
      fi
      ;;
    --email)
      if [ $# -gt 1 ]; then
        email=$2
        shift
      else
        echo "Option $1 requires an argument." >&2
        exit 1
      fi
      ;;
    --role)
      if [ $# -gt 1 ]; then
        if [ "$2" == "admin" ] || [ "$2" == "reader" ] || [ "$2" == "access" ]; then
          role=$2
          shift
        else
          echo "Error: invalid role '$2'. Role must be: 'admin', 'reader', 'access'" >&2
          exit 1
        fi
      else
        echo "Option $1 requires an argument." >&2
        exit 1
      fi
      ;;
    *)
      REST_ARGS+=("$1")
      ;;
  esac
  shift
done

# Check that the required arguments are present
if [[ -z $username ]]; then
  echo "Error: username is a required argument" >&2
  exit 1
fi

if [[ -z $password ]]; then
  echo "Error: password is a required argument" >&2
  exit 1
fi

if [[ -z $email ]]; then
  echo "Error: email is a required argument" >&2
  exit 1
fi

if [[ -z $role ]]; then
  echo "Error: role is a required argument" >&2
  exit 1
fi
set -- "${REST_ARGS[@]}"

oeeadminUser=$(c8y users list --includeAll --username "$username" -o csv --select "id" -n)

if [ -z "$oeeadminUser" ]; then
  echo "$username user was not detected, creating $username user."

  if [ "$role" == "admin" ]; then
    c8y users create -f -n --userName "$username" --password "$password" --email "$email" | \
    c8y userreferences addUserToGroup -f --group "business"   | \
    c8y userreferences addUserToGroup -f --group "OEE Admin"
  elif [ "$role" == "reader" ]; then
    c8y users create -f -n --userName "$username" --password "$password" --email "$email" | \
    c8y userreferences addUserToGroup -f --group "business"   | \
    c8y userreferences addUserToGroup -f --group "OEE Reader"
  elif [ "$role" == "access" ]; then
    c8y users create -f -n --userName "$username" --password "$password" --email "$email" | \
    c8y userreferences addUserToGroup -f --group "business"
  fi

  echo "Created $username user with permission $role successfully"

else
  echo "$username user is already exist on tenant $C8Y_HOST."
fi
