#!/usr/bin/env bash

help() {
  cat <<EOF
create an user with global roles "OEE Admin" and "OEE Reader"
EOF
}

export C8Y_SETTINGS_DEFAULTS_INSECURE='true'
export C8Y_TENANT="$C8Y_TENANT"
echo "Tenant ID : $C8Y_TENANT"
oeeadminUser=$(c8y users list --includeAll --username "oeeadmin" -o csv --select "id" -n)

if [ -z "$oeeadminUser" ]; then
  echo "oeeadmin user was not detected, creating oeeadmin user."

  echo "Create oeeadmin and add to Admin, business groups"
  c8y users create -f -n --userName "oeeadmin" --password "123aA@456" --email "dummy-oeeadmin@softwareag.com" | \
    c8y userreferences addUserToGroup -f --group "business"   | \
    c8y userreferences addUserToGroup -f --group "OEE Admin"  | \
    c8y userreferences addUserToGroup -f --group "OEE Reader"

else
  echo "oeeadmin user was already detected on tenant, will not create oee* users."
fi
