#!/usr/bin/env bash
help() {
  cat <<EOF
Generate a custom report about the status

Usage:
    c8y oee report create

Examples:
    $ c8y oee report create
    Create an overview report
EOF
}

REST_ARGS=()

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            help
            exit 0
            ;;

        *)
            REST_ARGS+=("$1")
            ;;
    esac
    shift
done

set -- "${REST_ARGS[@]}"

c8y api GET service/oee-bundle/configurationmanager/2/configuration "$@"
