#!/usr/bin/env bash
set -e

help() {
  cat <<EOF
List OEE profiles

Usage:
    c8y oee profiles list

    --id <string>           Match by name

Examples:
    c8y oee profiles get --id 12345
    # Get OEE profile
EOF
}

REST_ARGS=()

while [ $# -gt 0 ]; do
    case "$1" in
        --id)
            CONFIGURATION_ID="$2"
            shift
            ;;

        -h|--help)
            help
            exit 0
            ;;

        *)
            REST_ARGS+=("$1")
            ;;

    esac
    shift
done

set -- "${REST_ARGS[@]}"

c8y api GET "service/oee-bundle/configurationmanager/2/${CONFIGURATION_ID}" "$@"
